name: Build and Deploy
on:
  push:
    branches:
      - gh-pages
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy react app to github pages
      uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1
      env: 
        REACT_APP_OPENAI_KEY: ${{ secrets.REACT_APP_OPENAI_KEY }}
