name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build
      uses: actions/checkout@v2
    - run: |
        npm ci
        npm run build
      env:
        REACT_APP_OPENAI_KEY: ${{ secrets.REACT_APP_APIKey }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
