name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        npm install
        npm run-script build
      env:
        REACT_APP_OPENAI_KEY: ${{ secrets.REACT_APP_OPENAI_KEY }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        FOLDER: build
