name: Build and Deploy
on:
  push:
    branches:
      - gh-pages
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - run: npm ci
      shell: bash
    - run: npm deploy -- -u "github-actions-bot <support+actions@github.com>"
      shell: bash
      env: 
        REACT_APP_OPENAI_KEY: ${{ secrets.REACT_APP_OPENAI_KEY }}
